#pragma once

// Includes all RGL headers.

#include "Animator.h"
#include "base64.h"
#include "Button.h"
#include "DebugDraw.h"
#include "Debugger.h"
#include "Emitter.h"
#include "FileIO.h"
#include "FontManager.h"
#include "Game.h"
#include "GameObject.h"
#include "GameState.h"
#include "GameStateMachine.h"
#include "InputHandler.h"
#include "Layer.h"
#include "Level.h"
#include "LevelParser.h"
#include "MathHelper.h"
#include "ObjectFactory.h"
#include "ObjectLayer.h"
#include "ObjectParams.h"
#include "Particle.h"
#include "PhysicsObject.h"
#include "SimpleActor.h"
#include "SoundManager.h"
#include "TextureManager.h"
#include "TileLayer.h"
#include "tinyxml2.h"
#include "Vector2.h"